// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package custom_user

import (
	"gov2panel/api/custom_user"
)

type ControllerV1 struct{}

func NewV1() custom_user.ICustomUserV1 {
	return &ControllerV1{}
}
