// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package custom_public

import (
	"gov2panel/api/custom_public"
)

type ControllerV1 struct{}

func NewV1() custom_public.ICustomPublicV1 {
	return &ControllerV1{}
}
